language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mark-3110/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mark-3110/docker-react npm run test
